In [3]:
!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn
!pip install sklearn
!pip install nltk


     |████████████████████████████████| 1.4 MB 3.3 MB/s eta 0:00:01
     |████████████████████████████████| 662 kB 21.5 MB/s eta 0:00:01
     |████████████████████████████████| 69 kB 8.4 MB/s  eta 0:00:01
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434673 sha256=7902d454f01104940c8dee0770fced9a739efdb9ed1c7c0f13f0c54b55faf7b5
  Stored in directory: /home/jovyan/.cache/pip/wheels/45/6c/46/a1865e7ba706b3817f5d1b2ff7ce8996aabdd0d03d47ba0266
Successfully built nltk


In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

import re
pd.pandas.set_option('display.max_columns', None)

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /home/jovyan/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [5]:
df=pd.read_csv('data.csv', encoding= 'unicode_escape')
df.head()

Date  Label                                               Top1  \
0  2000-01-03      0  A 'hindrance to operations': extracts from the...   
1  2000-01-04      0                                          Scorecard   
2  2000-01-05      0                  Coventry caught on counter by Flo   
3  2000-01-06      1                      Pilgrim knows how to progress   
4  2000-01-07      1                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees?   
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by 'shambles' but lays blame on e...   
4                   Whingers - a formidable minority   

                                                Top9  \
0      Derby raise a glass to Strupar's debut double   
1  Hopkins 'furious' at Foster's lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England's decade of disasters   
4                             Alan Parker - part two   

                                      Top10  \
0  Southgate strikes, Leeds pay the penalty   
1                    Has Cubie killed fees?   
2            Blair Witch bandwagon rolls on   
3      Revenge is sweet for jubilant Cronje   
4                 Thuggery, Toxins and Ties   

                                   Top11  \
0  Hammers hand Robson a youthful lesson   
1                    A tale of two tails   
2         Pele turns up heat on Ferguson   
3                 Our choice, not theirs   
4   Met faces fresh attack on race crime   

                                               Top12  \
0                        Saints party like it's 1999   
1            I say what I like and I like what I say   
2         Party divided over Kohl slush fund scandal   
3  Profile of former US Nazi Party officer Willia...   
4          Everton fans top racist 'league of shame'   

                                               Top13  \
0                 Wear wolves have turned into lambs   
1                           Elbows, Eyes and Nipple

In [6]:
df.shape

(4101, 27)

In [7]:
df.isnull().sum()

Date     0
Label    0
Top1     0
Top2     0
Top3     0
Top4     0
Top5     0
Top6     0
Top7     0
Top8     0
Top9     0
Top10    0
Top11    0
Top12    0
Top13    0
Top14    0
Top15    0
Top16    0
Top17    0
Top18    0
Top19    0
Top20    0
Top21    0
Top22    0
Top23    1
Top24    3
Top25    3
dtype: int64

In [8]:
df=df.dropna()
df.shape

(4098, 27)

In [9]:
df.reset_index(inplace=True)

In [10]:
df.head(10)

index        Date  Label  \
0      0  2000-01-03      0   
1      1  2000-01-04      0   
2      2  2000-01-05      0   
3      3  2000-01-06      1   
4      4  2000-01-07      1   
5      5  2000-01-10      1   
6      6  2000-01-11      1   
7      7  2000-01-12      0   
8      8  2000-01-13      1   
9      9  2000-01-14      1   

                                                Top1  \
0  A 'hindrance to operations': extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   
5                                   Fifth round draw   
6                      Man Utd 2 - 0 South Melbourne   
7                Newcastle seek new football supremo   
8                   Bungling officials on the carpet   
9                  Pompey plump for Pulis work ethic   

                                                Top2  \
0                                          Scorecard   
1                                The best lake scene   
2                 United's rivals on the road to Rio   
3                                Thatcher facing ban   
4                     Beckham off but United survive   
5  BBC unveils secret weapon in ratings war: Sout...   
6  How North Atlantic drift could carry away Old ...   
7              Liverpool aim to speed up Heskey deal   
8  And in the red and raw corner it's 'Killer' Ma...   
9          Roma under fire over Rolexes for referees   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   
5                       Second Division round-up   
6          Buoyant BBC to show Brazil final live   
7                           Highlanders voted up   
8                United put their shirts on £30m   
9          Prenton Park Two told to take a break   

                                                Top4  \
0           Jack gets his skates on at ice-cold Alex   
1                                      Cheerio, boyo   
2      Police help Smith lay down the law at Everton   
3                    Leicester bin stadium blueprint   
4                                        Alan Parker   
5                                  European round-up   
6                Tranmere given all-clear in the Cup   
7               Edwards' power play suffers new blow   
8     England against plan for home nations' revival   
9  OK, I didn't figure in Rio but I'm still No1 w...   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   
5                      Third Division round-up   
6               United sit poorly with the Doc   
7                       Chelsea gamble on Weah   
8             Donald poised to quit Test scene   
9              Chelsea tune in to Weah's world   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   
5  Welfare could claim Killie tie as Caley Thistl...   
6           Queen's Park peril clouds Hampden future   
7                     Taylor settles the eternal tie   
8                        Adams stares into the abyss   
9                      Top storey awaits the Cottage   

                                                Top7  \
0            

In [11]:
df['combine']=df['Top1']+" "+df['Top2']+" "+df['Top3']+" "+df['Top4']+" "+df['Top5']+" "+df['Top6']+" "+df['Top7']+" "+df['Top8']+" "+df['Top9']+" "+df['Top10']+" "+df['Top11']+" "+df['Top12']+" "+df['Top13']+" "+df['Top14']+" "+df['Top15']+" "+df['Top16']+" "+df['Top17']+" "+df['Top18']+" "+df['Top19']+" "+df['Top20']+" "+df['Top21']+" "+df['Top22']+" "+df['Top23']+" "+df['Top24']+" "+df['Top25']

In [12]:
df['combine'][1]

"Scorecard The best lake scene Leader: German sleaze inquiry Cheerio, boyo The main recommendations Has Cubie killed fees? Has Cubie killed fees? Has Cubie killed fees? Hopkins 'furious' at Foster's lack of Hannibal appetite Has Cubie killed fees? A tale of two tails I say what I like and I like what I say Elbows, Eyes and Nipples Task force to assess risk of asteroid collision How I found myself at last On the critical list The timing of their lives Dear doctor Irish court halts IRA man's extradition to Northern Ireland Burundi peace initiative fades after rebels reject Mandela as mediator PE points the way forward to the ECB Campaigners keep up pressure on Nazi war crimes suspect Jane Ratcliffe Yet more things you wouldn't know without the movies Millennium bug fails to bite"

In [13]:
df.head()

index        Date  Label  \
0      0  2000-01-03      0   
1      1  2000-01-04      0   
2      2  2000-01-05      0   
3      3  2000-01-06      1   
4      4  2000-01-07      1   

                                                Top1  \
0  A 'hindrance to operations': extracts from the...   
1                                          Scorecard   
2                  Coventry caught on counter by Flo   
3                      Pilgrim knows how to progress   
4                               Hitches and Horlocks   

                                 Top2  \
0                           Scorecard   
1                 The best lake scene   
2  United's rivals on the road to Rio   
3                 Thatcher facing ban   
4      Beckham off but United survive   

                                            Top3  \
0                Hughes' instant hit buoys Blues   
1                  Leader: German sleaze inquiry   
2  Thatcher issues defence before trial by video   
3        McIlroy calls for Irish fighting spirit   
4                        Breast cancer screening   

                                            Top4  \
0       Jack gets his skates on at ice-cold Alex   
1                                  Cheerio, boyo   
2  Police help Smith lay down the law at Everton   
3                Leicester bin stadium blueprint   
4                                    Alan Parker   

                                          Top5  \
0       Chaos as Maracana builds up for United   
1                     The main recommendations   
2  Tale of Trautmann bears two more retellings   
3               United braced for Mexican wave   
4      Guardian readers: are you all whingers?   

                                                Top6  \
0  Depleted Leicester prevail as Elliott spoils E...   
1                             Has Cubie killed fees?   
2                                England on the rack   
3  Auntie back in fashion, even if the dress look...   
4                                   Hollywood Beyond   

                                              Top7  \
0                 Hungry Spurs sense rich pickings   
1                           Has Cubie killed fees?   
2  Pakistan retaliate with call for video of Walsh   
3                    Shoaib appeal goes to the top   
4                               Ashes and diamonds   

                                                Top8  \
0                  Gunners so wide of an easy target   
1                             Has Cubie killed fees?   
2               Cullinan continues his Cape monopoly   
3  Hussain hurt by 'shambles' but lays blame on e...   
4                   Whingers - a formidable minority   

                                                Top9  \
0      Derby raise a glass to Strupar's debut double   
1  Hopkins 'furious' at Foster's lack of Hannibal...   
2             McGrath puts India out of their misery   
3                      England's decade of disasters   
4                             Alan Parker - part two   

                                      Top10  \
0  Southgate strikes, Leeds pay the penalty   
1                    Has Cubie killed fees?   
2            Blair Witch bandwagon rolls on   
3      Revenge is sweet for jubilant Cronje   
4                 Thuggery, Toxins and Ties   

                                   Top11  \
0  Hammers hand Robson a youthful lesson   
1                    A tale of two tails   
2         Pele turns up heat on Ferguson   
3                 Our choice, not theirs   
4   Met faces fresh attack on race crime   

                                               Top12  \
0                        Saints party like it's 1999   
1            I say what I like and I like what I say   
2         Party divided over Kohl slush fund scandal   
3  Profile of former US Nazi Party officer Willia...   
4          Everton fans top racist 'league of shame'   

                                               Top13  \
0                 Wear wolve

In [18]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range (0, len(df)):
    review=re.sub('[^a-zA-Z]', ' ', df['combine'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [19]:
corpus[1]

'scorecard best lake scene leader german sleaz inquiri cheerio boyo main recommend cubi kill fee cubi kill fee cubi kill fee hopkin furiou foster lack hannib appetit cubi kill fee tale two tail say like like say elbow eye nippl task forc assess risk asteroid collis found last critic list time live dear doctor irish court halt ira man extradit northern ireland burundi peac initi fade rebel reject mandela mediat pe point way forward ecb campaign keep pressur nazi war crime suspect jane ratcliff yet thing know without movi millennium bug fail bite'

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500, ngram_range=(1,3))
x=cv.fit_transform(corpus).toarray()

In [21]:
y=df.Label
y.head()

0    0
1    0
2    0
3    1
4    1
Name: Label, dtype: int64

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

MULTINOMIAL NAIVE BAYES

In [23]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[213 204]
 [228 175]]
              precision    recall  f1-score   support

           0       0.48      0.51      0.50       417
           1       0.46      0.43      0.45       403

    accuracy                           0.47       820
   macro avg       0.47      0.47      0.47       820
weighted avg       0.47      0.47      0.47       820

accuracy_score:  0.47317073170731705


PASSIVE AGGRESSIVE CLASSIFIER

In [25]:
from sklearn.linear_model import PassiveAggressiveClassifier
clf=PassiveAggressiveClassifier()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[211 206]
 [199 204]]
              precision    recall  f1-score   support

           0       0.51      0.51      0.51       417
           1       0.50      0.51      0.50       403

    accuracy                           0.51       820
   macro avg       0.51      0.51      0.51       820
weighted avg       0.51      0.51      0.51       820

accuracy_score:  0.5060975609756098


XGBOOST

In [28]:
!pip install xgboost

     |████████████████████████████████| 148.9 MB 39 kB/s s eta 0:00:01MB/s eta 0:00:01�█▋ | 142.7 MB 54.6 MB/s eta 0:00:01


In [29]:
import xgboost

In [30]:
clf=xgboost.XGBClassifier()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)

In [31]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[189 228]
 [165 238]]
              precision    recall  f1-score   support

           0       0.53      0.45      0.49       417
           1       0.51      0.59      0.55       403

    accuracy                           0.52       820
   macro avg       0.52      0.52      0.52       820
weighted avg       0.52      0.52      0.52       820

accuracy_score:  0.5207317073170732


LOGISTIC REGRESSION

In [32]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [33]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print('accuracy_score: ', accuracy_score(y_test, y_pred))

[[209 208]
 [193 210]]
              precision    recall  f1-score   support

           0       0.52      0.50      0.51       417
           1       0.50      0.52      0.51       403

    accuracy                           0.51       820
   macro avg       0.51      0.51      0.51       820
weighted avg       0.51      0.51      0.51       820

accuracy_score:  0.5109756097560976
